---

- hosts: all
  become: true
  tasks:

  - name: update repository index on Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package on Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index on CentOS
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: intsall apache2 package on CentOS
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"
