---

- hosts: all
  become: true
  pre_tasks:

  - name: install update on Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update on CentOS
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: intsall mariadb package on CentOS#
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
