---

- hosts: all
  become: true
  pre_tasks:

  - name: install update on Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install update on CentOS
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package on Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache
    copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: start httpd on CentOS
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin lekhauhuutai48@gmail.com
    when: ansible_distribution == "CentOS"
    register: httpd_state

  - name: restart httpd on CentOS
    tags: httpd
    service:
      name: httpd
      state: restarted
    when: httpd_state.changed

  - name: intsall mariadb package on CentOS
    tags: mariadb
    yum:
      name: mariadb
      state: latest
      enabled: yes
    when: ansible_distribution == "CentOS"
