---

- hosts: all
  become: true
  pre_tasks:

  - name: install update on Ubuntu (update repo cache)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install update on CentOS (update repo cache)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for taile
    tags: always
    authorized_key:
      user: taile
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHFZK2ljsxL3fkdX8RzOzPhyEEl5ii1HyBh4lKrMxlCg ansible"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    tags: workstations
    package:
      name: unzip

  - name: install terraform
    tags: workstations
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.2/terraform_1.8.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php package on Ubuntu
    tags: install
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: copy
    copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: start httpd on CentOS
    tags: httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin lekhauhuutai48@gmail.com
    when: ansible_distribution == "CentOS"
    register: httpd_state

  - name: restart httpd on CentOS
    tags: httpd
    service:
      name: httpd
      state: restarted
    when: httpd_state.changed

  - name: install mariadb package on CentOS
    tags: install
    yum:
      name: mariadb
      state: latest
      enabled: yes
    when: ansible_distribution == "CentOS"
